apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imagebuilds.img.k8s.io
spec:
  group: img.k8s.io
  version: v1alpha1
  names:
    kind: ImageBuild
    plural: imagebuilds
  scope: Namespaced
  subresources:
    status: {}
